/* Main header */

#include "Definitions/defs.hpp"
#include "Arrays/array.hpp"
#include "Colorize/colors.hpp"
#include "Console/console.hpp"
#include "Maths/maths.hpp"
#include "Pixmap/pixmap.hpp"
#include "Files/files.hpp"
#include "Compress/compressors.hpp"
#include "System/system.hpp"
#include "Time/units.hpp"
#include "Gui/clipboard.hpp"
#include "Windows/window.hpp"
#include "Interpreter/asm.hpp"